# Generated by Django 2.0.5 on 2020-04-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
